version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_DEFAULT_LANGUAGE=en
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://read2rich:password@postgres:5432/read2rich
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - postgres
      - redis
      - kafka
      - qdrant

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=read2rich
      - POSTGRES_USER=read2rich
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

volumes:
  postgres_data: 